### ISSUE TITLE
Usage Example Video

### ISSUE THREAD

**Issue by lliuaotian** [m4xshen/example.nvim#1]
https://github.com/user-attachments/assets/88724a8f-1270-49b8-bc0e-0d9e7e00dcdf

**Comment by lliuaotian** [comment]
对不起，我上传错了，我以为是我仓库的

**Comment by m4xshen** [comment]
沒事 XD

**Comment by lliuaotian** [comment]
> 沒事 XD

谢谢你，根据你的example我写了一个我的小功能，非常感谢
